sequenceDiagram
    autonumber
    actor U as Klient
    participant R as Rower (IoT)
    participant S as Serwer Systemu
    participant P as Procesor Płatności
    participant A as Aplikacja Mobilna

    U->>R: Ręczne zamknięcie blokady (Lock)
    R->>R: Weryfikacja pozycji GPS
    R->>S: Sygnał: Zablokowano (ID_roweru, GPS, Czas)
    S->>S: Obliczanie czasu i kosztu przejazdu
    S->>P: Zlecenie pobrania opłaty (Finalizacja)
    P-->>S: Potwierdzenie transakcji
    S->>S: Zmiana statusu roweru na 'Dostępny'
    S-->>A: Przesłanie podsumowania (Trasa, Koszt)
    A-->>U: Wyświetlenie paragonu i prośba o ocenę